
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-observability-redhat-com-v1-observability
  failurePolicy: Fail
  name: vobservability.kb.io
  rules:
  - apiGroups:
    - observability.redhat.com
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - observabilities
