apiVersion: observability.redhat.com/v1
kind: Observability
metadata:
  name: observability-sample
spec:
  resyncPeriod: 30s
  configurationSelector:
    matchLabels:
      configures: "observability-operator"