apiVersion: observability.redhat.com/v1
kind: Observability
metadata:
  name: observability-sample
spec:
  observatorium:
    gateway: "https://observatorium-observatorium.apps-crc.testing"
    tenant: "test"
    authType: "dex"
    dexConfig:
      url: "http://dex-dex.apps-crc.testing"
      credentialSecretNamespace: "kafka-observability"
      credentialSecretName: "observatorium-dex-credentials"