apiVersion: v1
kind: Secret
metadata:
  name: kafka-observability-configuration
  namespace: kafka-observability
  labels:
    configures: observability-operator
data:
  access_token: <ADD BASE64 CONVERTED TOKEN HERE>
  channel: ZGV2ZWxvcG1lbnQ=
  repository: aHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy9iZjJmYzZjYzcxMWFlZTFhMGMyYS9vYnNlcnZhYmlsaXR5LXJlc291cmNlcy1tay9jb250ZW50cw==
type: Opaque