apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: observability-operator-secret-crc
  annotations:
    description: "Observability Operator Secret for CRC"
parameters:
- name: DATASOURCES
  description: YAML file containing datasources config
- name: PROMETHEUS
  description: YAML file containing Prometheus datasource config
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: grafana-datasources
    namespace: openshift-monitoring
  data:
    datasources.yaml: >-
      ICAgICAgewogICAgICAJImRhdGFzb3VyY2VzIjogW3sKICAgICAgCQkiYmFzaWNBdXRoUGFzc3dvcmQiOiAidGVzdCIsCiAgICAgIAkJImJhc2ljQXV0aFVzZXIiOiAidGVzdCIKICAgICAgCX1dCiAgICAgIH0=
    prometheus.yaml: >-
      ICAgICAgewogICAgICAJImRhdGFzb3VyY2VzIjogW3sKICAgICAgCQkiYmFzaWNBdXRoUGFzc3dvcmQiOiAidGVzdCIsCiAgICAgIAkJImJhc2ljQXV0aFVzZXIiOiAidGVzdCIKICAgICAgCX1dCiAgICAgIH0=
  type: Opaque