apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: observability-operator-secrets
  annotations:
    description: "Observability Operator Secrets"
parameters:
- name: OBSERVATORIUM_TENANT
  description: Tenant for Observatorium
- name: OBSERVATORIUM_GATEWAY
  description: Gateway for Observatorium
- name: OBSERVATORIUM_AUTH_TYPE
  description: Authentication type for Observatorium
- name: OBSERVATORIUM_RHSSO_URL
  description: URL for Redhat SSO
- name: OBSERVATORIUM_RHSSO_REALM
  description: Realm for Redhat SSO
- name: OBSERVATORIUM_RHSSO_METRICS_CLIENT_ID
  description: Red Hat SSO Metrics client id
- name: OBSERVATORIUM_RHSSO_METRICS_SECRET
  description: Red Hat SSO Metrics secret
- name: OBSERVATORIUM_RHSSO_LOGS_CLIENT_ID
  description: Red Hat SSO Logs client id
- name: OBSERVATORIUM_RHSSO_LOGS_SECRET
  description: Red Hat SSO Logs secret
- name: GITHUB_ACCESS_TOKEN
  description: Access token for the observability resources configuration repo
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: observatorium-configuration-red-hat-sso
  stringData:
    tenant: ${OBSERVATORIUM_TENANT}
    gateway: ${OBSERVATORIUM_GATEWAY}
    authType: ${OBSERVATORIUM_AUTH_TYPE}  
    redHatSsoAuthServerUrl: ${OBSERVATORIUM_RHSSO_URL}
    redHatSsoRealm: ${OBSERVATORIUM_RHSSO_REALM}
    metricsClientId: ${OBSERVATORIUM_RHSSO_METRICS_CLIENT_ID}
    metricsSecret: ${OBSERVATORIUM_RHSSO_METRICS_SECRET}
    logsClientId: ${OBSERVATORIUM_RHSSO_LOGS_CLIENT_ID}
    logsSecret: ${OBSERVATORIUM_RHSSO_LOGS_SECRET}
  type: Opaque
- kind: Secret
  apiVersion: v1
  metadata:
    name: kafka-observability-configuration
    labels:
      configures: observability-operator
  stringData:
    access_token: ${GITHUB_ACCESS_TOKEN}
    channel: resources
    tag: main
    repository: >-
      https://api.github.com/repos/bf2fc6cc711aee1a0c2a/observability-resources-mk/contents
- kind: Secret
  apiVersion: v1
  metadata:
    name: redhat-managed-kafka-pagerduty
  data:
    PAGERDUTY_KEY: ZHVtbXk=
  type: Opaque
- kind: Secret
  apiVersion: v1
  metadata:
    name: redhat-managed-kafka-deadmanssnitch
  data:
    SNITCH_URL: aHR0cDovL2R1bW15
  type: Opaque
